name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Update to v3 for Node.js 20 support

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Update to v4 for Node.js 20 support
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory static files (e.g., index.html)
